### ISSUE TITLE
sightlines in `map` crashes docker instance

### ISSUE THREAD

**Issue by gacafe** [diagonalworks/diagonal-b6#43]
```
camden_wkt = "POLYGON ((-0.15398025512695315 51.548790301633545,-0.1508903503417969 51.51750259650433,-0.10608673095703128 51.51792987720296,-0.10883331298828126 51.54782956596529,-0.15398025512695315 51.548790301633545))"
camden =  b6.wkt(camden_wkt)
benches = b6.find_points( b6.intersecting(camden).and_(b6.tagged("#amenity","bench")) )
benches_sightline_areas = benches.map( lambda b: b.sightline(100).area() )
w(benches_sightline_areas)
```

crashes docker with the following message:

```
panic: Can't split edges that don't cross the reference

goroutine 99 [running]:
diagonal.works/b6/api/functions.(*polarEdge).Split(0xc0007576e8?, {{{0x3fe3e96c99cc3180, 0xbf56fa1f5c403792, 0x3fe90ce0a6546719}}, {{0x3fe3e96cfe9edd8b, 0xbf56fb84a52cb70e, 0x3fe90ce055de3fb8}}}, {{0x3fe3e91070b91809?, 0xbf57309301c5507e?, 0x3fe90d29da351346?}})
        /build/src/diagonal.works/b6/api/functions/sightline.go:521 +0x3b6
diagonal.works/b6/api/functions.SightlineUsingPolarCoordinates2({{0xd1f060?, 0xde7660?, 0xd1f000?}}, 0x3ef07563ab9727ce, {0xf618e8, 0xc000552000})
        /build/src/diagonal.works/b6/api/functions/sightline.go:676 +0x135b
diagonal.works/b6/api/functions.Sightline(...)
        /build/src/diagonal.works/b6/api/functions/sightline.go:26
diagonal.works/b6/api/functions.sightline({0x7f89be06c9c0?, 0xc00067a380?}, 0x4059000000000000, 0xc0009f2c00)
        /build/src/diagonal.works/b6/api/functions/sightline.go:22 +0x5a
reflect.Value.call({0xce5a60?, 0xe7b618?, 0x44e296?}, {0xe2827a, 0x4}, {0xc00083a2a0, 0x3, 0x4?})
        /usr/local/go/src/reflect/value.go:586 +0xb0b
reflect.Value.Call({0xce5a60?, 0xe7b618?, 0x13?}, {0xc00083a2a0?, 0xe27540?, 0xf618e8?})
        /usr/local/go/src/reflect/value.go:370 +0xbc
diagonal.works/b6/api.goCall.CallFromStack({{0xce5a60, 0xe7b618, 0x13}, {0xc000842170, 0x9}}, 0x2, {0x158acb8, 0xc000759308?, 0x0}, 0xc0009f2c00)
        /build/src/diagonal.works/b6/api/vm.go:427 +0x6ca
diagonal.works/b6/api.(*VM).execute(0xc00048c380, 0xc0009f2c00)
        /build/src/diagonal.works/b6/api/vm.go:379 +0x41f
diagonal.works/b6/api.(*lambdaCall).CallFromStack(0x0?, 0xc000759498?, {0xc000966600, 0x20, 0x20}, 0x40f608?)
        /build/src/diagonal.works/b6/api/vm.go:522 +0x1c5
diagonal.works/b6/api.(*lambdaCall).CallWithArgs(0x9a6cf3?, {0xc000554140?, 0x1, 0xc00006e800?}, {0xc000966600, 0x20, 0x20}, 0xc0009f2c00)
        /build/src/diagonal.works/b6/api/vm.go:543 +0x279
diagonal.works/b6/api.Call1({0xde7660?, 0xc00067a380}, {0xf5d890, 0xc0008421d0}, 0x0?)
        /build/src/diagonal.works/b6/api/vm.go:73 +0xb6
diagonal.works/b6/api/functions.glob..func1.1({0xde7660?, 0xc00067a380?}, 0xa21982?)
        /build/src/diagonal.works/b6/api/functions/functions.go:143 +0x31
diagonal.works/b6/api/functions.(*mapCollection).Next(0xc00067b740)
        /build/src/diagonal.works/b6/api/functions/map.go:28 +0x62
diagonal.works/b6/api.collectionToProto({0xf51240?, 0xc00067b700?})
        /build/src/diagonal.works/b6/api/protos.go:288 +0xd5
diagonal.works/b6/api.ToProto({0xd47400, 0xc00067b700?})
        /build/src/diagonal.works/b6/api/protos.go:172 +0x19bd
diagonal.works/b6/grpc.(*service).Evaluate(0xc000652000, {0xc000d5df20?, 0x517286?}, 0x0?)
        /build/src/diagonal.works/b6/grpc/service.go:41 +0x17d
diagonal.works/b6/proto._B6_Evaluate_Handler({0xcee220?, 0xc000652000}, {0xf5c5c8, 0xc000d5def0}, 0xc0007157a0, 0x0)
        /build/src/diagonal.works/b6/proto/api_grpc.pb.go:83 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00059c000, {0xf61398, 0xc0005391e0}, 0xc000380c60, 0xc000652090, 0x153ed00, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc00059c000, {0xf61398, 0xc0005391e0}, 0xc000380c60, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /root/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /root/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

```
I think it happens on the edges of the data because when you pick smaller areas that are well contained in the data - not on the edges - then I did not see the error.

**Comment by gacafe** [comment]
was trying to decode if a particular bench was culprit but then ran into https://github.com/diagonalworks/diagonal-b6/issues/42#issue-1732572648
